modLoader = "javafml"
loaderVersion = "[36,)"
license = "LGPLv3"
issueTrackerURL = "https://github.com/GoryMoon/HorsePower/issues"

[[mods]]
modId = "horsepower"
version = "${file.jarVersion}"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/horse-power"
displayName = "Horse Power"
credits = "Darkosto for coming up with the idea"
authors = "Gory_Moon, Terpo"
description = '''
A mods that adds horse powered blocks.
'''

[[dependencies.horsepower]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.horsepower]]
    modId="minecraft"
mandatory = true
versionRange = "[1.16.5,1.17)"
ordering = "NONE"
    side="BOTH"

[[dependencies.horsepower]]
    modId="jei"
mandatory = false
versionRange = "[7.7.1,)"
ordering = "AFTER"
    side="BOTH"

[[dependencies.horsepower]]
    modId="waila"
mandatory = false
versionRange = "[1.10.11,)"
ordering = "AFTER"
    side="BOTH"

[[dependencies.horsepower]]
    modId="theoneprobe"
mandatory = false
versionRange = "[1.16-3.1.4,)"
ordering = "AFTER"
    side="BOTH"
